### ISSUE TITLE
Разместить код подписки на вторую рассылку

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#123]
Код здесь: https://subscribe.ru/manage/author/quick?gid=business.tech.bizprogramming

**Comment by unpete** [comment]
В каком месте и в каком виде разместить?
Есть вариант с формулами #119, который позволит подключить разные модули к разным статьям.

**Comment by nmivan** [comment]
Я думаю, заморачиваться не надо пока - просто рядом положить, справа например.
