### ISSUE TITLE
Линейный график

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#145]
Вот пример:
![image](https://user-images.githubusercontent.com/29771561/44336418-cdcfe580-a490-11e8-884f-446744a9d5b8.png)

Точки - это даты (в данном случае - месяцы)
Серии - тип задач (в данном случае их три)

**Comment by unpete** [comment]
Под анонимусом, `reports/chart|thrid`

**Comment by nmivan** [comment]
Збс
