### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#147]
Как ты учил, сохранил в смартфоне ссылку на business-programming на главном экране. Все хорошо, только он 404 выдает - судя по всему, автоматически пытается найти страницу index.html, а ее нет.

Заглушку бы сделать, или как-то выкрутиться, потому что ярлык на рабочем столе выглядит очень круто.

**Comment by unpete** [comment]
Удаление и повторное создание ярлыка на главном экране, должно решить проблему

**Comment by nmivan** [comment]
Збс
