### ISSUE TITLE
Сделать пример линейного графика с картинками (svg)

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#158]

**Comment by unpete** [comment]
Доступна на отладочном сайте https://flowcon.oknosoft.ru/flowcon/diagram
Работает только в хроме - время на другие браузеры пока не трачу.

**Comment by nmivan** [comment]
Бросается в глаза несоответствие линии и цифр над бутылками. Понимаю, что линия - про другие цифры.
Может, две линии вывести? Добавить ту, которая соединит бутылки по показателю "тыс. шт."

**Comment by unpete** [comment]
У заказчика в оригинале 2 линии и бар, я вывел линию и бар
https://github.com/unpete/private/issues/262

**Comment by nmivan** [comment]
А, понятно. Все по ТЗ.
