### ISSUE TITLE
Диаграммы в несколько колонок

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#159]

**Comment by unpete** [comment]
- Отдельный абстрактный компонент, который ничего не знает про диаграммы и раскидывает членов коллекции `children` по ячейкам
- Имеет сохраненные настройки + параметр `grid` в url. `Url` имеет более высокий приоритет, что позволит формировать ссылки на конкретный набор диаграмм или иных компонентов
- На узких экранах, меньше 600px, располагает детей в одну колонку
- Умеет рассказывать внешнему компоненту через `connect` о своём текущем layout-е и какие бывают layout-ы

**Comment by unpete** [comment]
Кнопку управления разместил справа на панели инструментов приложения - появляется на странице диаграмм.
Настройки пока не запоминаются - про это отдельная задача.
Раскладка по ссылке уже работает. Например, [diagram?grid=23](https://business-programming.ru/flowcon/diagram?grid=23) сделает две колонки в первом ряду и 3 в остальных

**Comment by nmivan** [comment]
Бля, это охуенно.
