### ISSUE TITLE
Одна диаграмма для пользователя flowcon

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#164]
1. Должен появляться default
2. В нем должна быть указана одна диаграмма, например "doc/chart|Test"
3. Ну, она наверное по умолчанию нарисуется.

**Comment by unpete** [comment]
- добавить 2 документа в шаблон базы
- доработать ddoc, чтобы пользователь без подписки не мог править список диаграмм
- обновить базы имеющихся пользователей
