### ISSUE TITLE
Описать метаданные флакона (ближайшие, для js=1С)

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#17]

**Comment by unpete** [comment]
1С-ная заготовка здесь: \\\\FILE-SRV\\work\\0KNOSOFT\\0ВНУТР\\FLOWCON
Dt-шка этой заготовки: \\\\FILE-SRV\\backup\\ОКНОСОФТ\\FLOWCON

**Comment by unpete** [comment]
обновил cf и dt

**Comment by nmivan** [comment]
Убираем старые задачи
