### ISSUE TITLE
вопросы по 1С-части

### ISSUE THREAD

**Issue by unpete** [oknosoft/flowcon#172]
- Не все объекты включены в подсистему Flowcon
- Регл. задание по умолчанию 60 секунд и http-timeout 60 секунд - при недоступности сети будет колбасить без перерывов. Может, 90 или 120 сделать
- Зачем в сугубо серверном модуле директивы &НаСервере, а в клиентском модуле, директивы &НаКлиенте
- Почему модуль флКлиент только для обычного приложения
- Функция `ИмяКорректно(Имя)` - couchdb не разрешает `_` в первой позиции имени реквизита

**Comment by nmivan** [comment]
Исправил
