### ISSUE TITLE
StackedBarChart

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#177]
Уже очень нужен вот такой бар: http://recharts.org/en-US/examples/StackedBarChart

**Comment by unpete** [comment]
Формат объекта почти такой же, как для обычного бара, отличается только описание серий: в них можно добавлять поля `stack` со строковым ключом. Бары с одинаковым стеком - суммируются.
Пример объекта:
````javascript
  "series": [
    {
      "name": "pv",
      "color": "#7f7f7f",
      "stack": "a"
    },
    {
      "name": "uv",
      "color": "#ff7f0e",
      "stack": "a"
    }
  ],
````
Пример диаграммы: [седьмая](https://flowcon.oknosoft.ru/flowcon/diagram?grid=3) на отладочном сервере
