### ISSUE TITLE
Создать метаданные в 1С, выгрузить в CouchDB, настроить синонимы и способы кеширования

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#19]

**Comment by unpete** [comment]
В текущей dt-шке стартовые вещи настроены `\\FILE-SRV\backup\ОКНОСОФТ\FLOWCON`
В "мир" dt-шку публиковать не надо - там пароль от публичной couchdb.

**Comment by nmivan** [comment]
Убираем старые задачи
