### ISSUE TITLE
Высота table

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#192]
Как регулировать высоту таблицы?
Сейчас выглядит вот так (скриншот из трехколоночного дашборда):
![image](https://user-images.githubusercontent.com/29771561/45016385-e833c280-b03d-11e8-99a5-791b8988bd56.png)

Можно сделать так, чтобы высота таблицы соответствовала количеству строк? И чтобы полосы прокрутки не было?

**Comment by nmivan** [comment]
И на фуллскрине таблица какая-то косоёбая получается:

![image](https://user-images.githubusercontent.com/29771561/45016556-6f813600-b03e-11e8-8423-0c279c071993.png)

**Comment by unpete** [comment]
Новый `muitable` решает эту задачу
