### ISSUE TITLE
Название страницы, которой делишься

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#199]
Не знаю терминологии, но когда делишься какой-то страницей business-programming.ru, всегда получается вот так:
![image](https://user-images.githubusercontent.com/29771561/45025676-8e3ef700-b055-11e8-9689-9aa5a2dca634.png)

Ссылка-то правильная, ведет куда надо, но название всегда одно и то же.

**Comment by nmivan** [comment]
Там есть какой-то фокус. Например, когда делишься с ИС, выглядит вот так:
![image](https://user-images.githubusercontent.com/29771561/45026216-15409f00-b057-11e8-9ef4-9da7af8d371a.png)

Виден и заголовок статьи, и вводный текст, и картинка.

**Comment by unpete** [comment]
Разобрался.
У нас клиентский рендеринг, а facebook ленится выполнять скрипты - использует body и title по умолчанию. Можно написать скрипт для создания сохранённых копий всех страниц. Это решит проблему и понравится старым поисковым машинам типа Рамблера.

**Comment by nmivan** [comment]
Тут тебе виднее. Но если названия будут правильными, блог станет красивее.

**Comment by unpete** [comment]
Пользы от смешанного рендеринга не очень много: улучшатся позиции в поисковиках и ссылки в социальных сетях.
Но задача интересная. Можно будет хвастаться, что в метадате поддержан смешанный рендеринг. Вероятность, что подобное появится в вордпрессе или битриксе, близка к нулю.

**Comment by unpete** [comment]
Cделал пререндер и добавил facebook-специфичных тегов.
Если начать заполнять в статьях h1, title и description разным текстом - ссылки в соцсетях и поисковиках станут красивее.
- h1 - это заголовок на странице
- title - это заголовок в закладке браузера
- description - краткое описание

В prod пока не запущено, #200, #201
