### ISSUE TITLE
В ключах параметров не работает вид сравнения "В списке" для строк

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#2]
Например, не получается несколько репозиториев засунуть

**Comment by unpete** [comment]
Вариант сделать репозитории ссылочным типом "Значения свойств объектов" не нравится?
Ведь сам параметр "репозиторий" уже есть.

**Comment by nmivan** [comment]
Нет конечно, для драйвера гитхаба это лишнее.

**Comment by unpete** [comment]
Сделать абстрактно-универсально на стороне 1С не получится.
Событие получения формы, которое я перехватываю, чтобы нарисовать список, возникает только для значений ссылочных типов.
Понятно, что можно залезть в код других форм или редактировать строку со списком значений руками
