### ISSUE TITLE
Визуальный компонент оглавления - заготовка

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#205]

**Comment by unpete** [comment]
Для начала, добавим компоненту `Список статей`, три параметра url:
- tags - список гвидов тегов
- view - если равно `contents`, показываем оглавление, если пусто или `raw` - обычный список
- search - если не пусто, фильтруем по подстроке

**Comment by unpete** [comment]
параметра `view` не будет, делаем отдельный раздел в навигации `/contents/`
