### ISSUE TITLE
Личный флакон: метаданные + базовый интерфейс

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#237]
1. Потоки
2. Виды активностей
3. Активности (документ)

**Comment by unpete** [comment]
В качестве _Потоков_, можем использовать _Категории тегов_, тогда их не надо доставлять в каждую базу пользователя, редактируем централизовано.
_Виды активностей_ и _Активности_ - новые сущности, хранятся в _doc_, пользователь может их редактировать
