### ISSUE TITLE
Битые ссылки в письмах с регистрацией

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#238]
Один человек написал мне в соц.сетях, что не может зарегистрироваться.
Я поспрашивал - говорит, в письме ссылка битая.
Я тоже попробовал зарегиться, имя пользователя 1opinion. Ссылка пришла: https://business-programming.ru/auth/confirm-email/z4TnaWvCTQe00OKY98zH8w, по ней - 404.

**Comment by nmivan** [comment]
Пользователь создался, база есть.

**Comment by unpete** [comment]
Ссылка как раз, хорошая, а вот nginx или подключенный сегодня serviceworker (что более вероятно) криво маршрутизирует - завтра поправлю.

**Comment by unpete** [comment]
Первый вход на business-programming будет со старым кешем.
При последующих, навигация отработает корректно.
Перешел по ссылке из первого сообщения - получил ответ об успешном подтверждении email.
При втором и последующих, ожидаемый invalid_token, т.к. email уже подтверждён.
