### ISSUE TITLE
Не работают диаграммы обычных пользователей

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#239]
Сделал обработку выкладывания диаграмм, а они в сервисе не рисуются.
Алгоритм такой:
1. Захожу в сервис без авторизации, диаграммы есть;
2. Авторизуюсь, возвращаюсь в дашборды, показываются диаграммы из демозоны;
3. Обновляю страницу (F5), вылезают ошибки в консоли.

![image](https://user-images.githubusercontent.com/29771561/45648711-c5e08100-bae2-11e8-8919-4408d978832b.png)

**Comment by unpete** [comment]
обновил service-worker.
Если после двух перезапусков браузера проблема сохранится, говори под каким пользователем смотреть - под unpete всё ок.

**Comment by nmivan** [comment]
Пользователь 1opinion
Пароль 123456

**Comment by unpete** [comment]
Пойдя по грибы набрал много ягод, пришлось переработать методы получения списка баз и диаграмм, доступных в этих базах - вроде, работает, проверяй.

Пустой массив `charts_available` в настройках пользователя - это нормально, пока диаграмм мало.
Если сейчас обработка 1С не заботится об этом массиве, надо доработать.

Еще, были глюки с сетевыми запросами. Если подтвердится, создадим отдельную задачу.

**Comment by nmivan** [comment]
Проверил, закрываю.
