### ISSUE TITLE
Учесть acl при формировании публичных диаграмм

### ISSUE THREAD

**Issue by unpete** [oknosoft/flowcon#259]
https://github.com/oknosoft/flowcon/issues/248#issuecomment-423754863
Иначе, пульс окнософта и стоимость балла никто не увидит.
В приватных диаграммах, acl не учитывается, но можно проставить - вреда не будет.

**Comment by unpete** [comment]
Значения, которые точно нужны в списке:
- _anonymous
- r_charts_editor
- r_doc_editor
- r_remote_editor
- r_subscribers

**Comment by unpete** [comment]
> при формировании публичных диаграмм

Уточню: при работе с любыми объектами в базах под ACL

**Comment by nmivan** [comment]
Учел. Ща обновлю рабочую, посмотрим, что получится.
