### ISSUE TITLE
endpoint получения проверок

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#297]
Сейчас селектор, если что, выглядит так:

"{
	|""selector"": {
	|	""sorting_field"": {""$gte"": 0},
	|	""tags"": {
	|	""$elemMatch"": {
	|		""$in"": [" + СтрокаТегов + "]
	|				}
	|			}
	|	},
	|""fields"": [""_id"", ""id"", ""name"", ""h1"", ""introduction"", ""date"", ""author"", ""tags"", ""acl"", ""_attachments"", ""content"", ""version_from"", ""version_till""],
	|""use_index"": ""sorting_field_tags""
	|}";

**Comment by unpete** [comment]
Добавляем endpoint `post /user/proxy`.
Проксировать он будет в couchdb, к которой подключен superlogin с теми же заголовками, включая авторизацию, которые были у исходного запроса. Единственное отличие - из тела будет вырезан bom.
URL для couchdb, добавляем в строку адреса `post /user/proxy?url=fl_0_remote/_find`

**Comment by unpete** [comment]
http://192.168.9.160:3001/user/proxy?url=fl_0_remote/_find
