### ISSUE TITLE
Выбор в поле ввода без клавиатуры

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#313]
Или я не умею, или выбор делается только клавиатурой (кнопка "стрелка вниз"). Неудобно, приходится снимать руку с мыши.

**Comment by nmivan** [comment]
Например, инициатор и исполнитель задачи.

**Comment by unpete** [comment]
основная часть готова, остались проблемы на мобильных устройствах и рассинхронизация фокуса при возврате из диалога

**Comment by unpete** [comment]
https://github.com/oknosoft/metadata.js/commit/f084104dda3abfa3f60a173b2046d645de89d5e6
