### ISSUE TITLE
Картинки к статьям при расшаривании

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#326]
На Инфостарте как-то сделано, что при расшаривании автоматом ставится картинка статьи.
У нас, из-за того, что статей много, они сливаются - картинка везде одинаковая, наш флакон.
Может, разнообразить как-то?

**Comment by unpete** [comment]
Ок, добавим в статью реквизит, в котором будет можно указать url картинки для соцсетей.
Возможно, и для внутренних целей пригодится - если захотим в содержании картинки показывать.

**Comment by unpete** [comment]
Реквизит в метаданные и на форму добавил - можно заполнять, поддержка при расшаривании будет чуть позже.
