### ISSUE TITLE
Проверить работу ACL

### ISSUE THREAD

**Issue by unpete** [oknosoft/flowcon#331]
В статьях и прочих режимах, для анонимусов и авторизованных, из 1С и браузера

**Comment by unpete** [comment]
Роли текущего пользователя видны в `$p.superlogin.getSession()`

**Comment by nmivan** [comment]
Проверял на статье https://business-programming.ru/articles/check_data_pay.
Поставил в ней одну роль - r_subscribers, зашел в инкогнито, без авторизации - статья видна в списке, зайти в нее получилось.

**Comment by unpete** [comment]
Там c ACL всё в порядке, но индекс прикольный - он готовую иерархию хранит. Отфильтрую на стороне браузера. Безопасность не пострадает.

**Comment by nmivan** [comment]
да список пофиг, я его так, к слову упомянул. Главное - статья доступна для прочтения анонимусу.

**Comment by unpete** [comment]
#334
https://github.com/oknosoft/covercouch/commit/4470c0ec51e792614a4f9fbf3c60e1b98f494111
https://github.com/oknosoft/covercouch/commit/70082683f5bc913afd67eb13c4bfeed461842819

Должно заработать и в списке и для конкретного документа.
Документ check_data_pay сейчас не виден даже в списке редактирования и недоступен для изменения из интерфейса. Ты выстрелил себе в ногу, оставив единственную роль `r_subscribers`, которой нет у пользователя `nmivan`.
Добавить себе роль и отредактировать acl документа можно через futon.
Доступ к футону надо будет ограничить по ip, чтобы пользователи не могли со своей учеткой обойти acl-proxy `business-programming.ru/couchdb/fl_`

**Comment by nmivan** [comment]
я думал, там как в 1С, права более высокого уровня включают в себя права более низких уровней доступа.

**Comment by unpete** [comment]
> права более высокого уровня

А уровень по буквам в названии роли определять?
Так сделать можно, но текущий алгоритм мне нравится больше.
