### ISSUE TITLE
Сортировка в оглавлении

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#343]
Странным образом сбилась сортировка, например здесь - https://business-programming.ru/contents/easier_than_it_seems
Главы идут вразнобой, хотя поле "Порядок" вроде правильно заполнено. Посмотрел первые четыре статьи, у них поле "Порядок" 950, 908, 930, 916.

**Comment by unpete** [comment]
Это из-за RLS.
Сырой индекс couchdb возвращает отсортированный результат.
Индекс без reduce, пропущенный через RLS, так же, остаётся корректно отсортированным, просто, из него могут выпасть некие строки.
Свёртка индекса с reduce, выполняется ACL-proxy, который теряет сортировку.
Править covercouch сейчас не буду, поставлю заплату в сам floucon.
