### ISSUE TITLE
Активность. Создание новой активности

### ISSUE THREAD

**Issue by nikitkuzi** [oknosoft/flowcon#361]
Заметил такой баг: когда создаешь новую активность, и не изменяешь дефолтный поток (Здоровье), то она не высвечивается на главной странице в разделе здоровье. Еще было бы хорошо добавить возможность открывать ссылку в новой вкладке. Так же было бы удобно моментальное удаление активности. Например случайно создал активность и хочется ее удалить, без дальнейшего обновления страницы

**Comment by unpete** [comment]
Спасибо, поправим на следующей неделе.
