### ISSUE TITLE
Ошибка при создании задачи

### ISSUE THREAD

**Issue by GanyaT** [oknosoft/flowcon#362]
В общем, зарегестрировалась для использования сервиса активностей. Слева в меню увидела "Задачи". Не разбиралась, для чего они, решила попробовать создать, чтобы понять, повлияет ли это на активности (там ведь были какие-то баллы)

В общем после того как нажала "сохранить и закрыть" Задачи больше не открываются
висит ссылка с адресом https://business-programming.ru/doc.issue/list и ничего не происходит, в окне абсолютно пусто, даже не выдаёт ошибки. Приходится ручками возвращаться на основной сайт. 

В общем никогда такого не было и вот опять я всё сломала, объясните, что я сделала не так, пожалуйста))

Ну и если я написала не по адресу, прошу прощения)

**Comment by GanyaT** [comment]
Хм, когда нажимаю "задачи" там быстро выскакивает ошибка (скрин) и после этого всё окно браузера становится пустым. 

https://pp.userapi.com/c845220/v845220628/14a0b2/Xy37dMLhkvI.jpg

**Comment by unpete** [comment]
Благодарю за информацию.
Интерфейс задач сейчас в активной разработке, возможны любые ошибки.
