### ISSUE TITLE
Книга "Infinite scale". Выборы, выборы... Опечатка

### ISSUE THREAD

**Issue by d666l** [oknosoft/flowcon#363]
Возможно в абзаце 

[— Потому что только упырь может выбирать задачу целый день. – засмеялся Джон. – У людей жизнь короткая, надо много успеть, а упырю – все нипочем, перед ним целая вечность. Может хоть неделю выбирать задачу, чтобы потом ее за час сделать.]

вместо "засмеялся Джон" необходимо "засмеялся Крис"

**Comment by nmivan** [comment]
Да, вы правы, спасибо.

**Comment by d666l** [comment]
Пожалуйста! Спасибо, за всё ваше творчество. Читаю каждый рассказ и с нетерпением жду продолжения каждой книги.

**Comment by nmivan** [comment]
Спасибо :)

**Comment by d666l** [comment]
Если будет возможность поправьте и на business-programming.ru

**Comment by nmivan** [comment]
Точно, про него забыл. Спасибо.
