### ISSUE TITLE
Текст "Дурилка картонная. Цифровая"

### ISSUE THREAD

**Issue by nmivan** [oknosoft/flowcon#55]
https://business-programming.ru/articles/Cardboard_durilka_Digital.

**Comment by unpete** [comment]
Предлагаю воздерживаться от использования заглавных букв в url

**Comment by unpete** [comment]
Да еще и с точкой в конце - это бяка какая-то, а не url

**Comment by nmivan** [comment]
Ок, случайно вышло.
